/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#66768d",
        "surface-container-high": "#e6e8ea",
        "primary-fixed-dim": "#6bd8cb",
        "primary": "#00685f",
        "surface-tint": "#006a61",
        "on-primary": "#ffffff",
        "secondary-fixed": "#dae2fd",
        "surface-bright": "#f7f9fb",
        "tertiary-fixed-dim": "#b7c8e1",
        "surface-container-highest": "#e0e3e5",
        "on-surface-variant": "#3d4947",
        "on-secondary-fixed-variant": "#3f465c",
        "background": "#f7f9fb",
        "on-surface": "#191c1e",
        "secondary-fixed-dim": "#bec6e0",
        "surface-variant": "#e0e3e5",
        "on-tertiary-fixed-variant": "#38485d",
        "outline": "#6d7a77",
        "error-container": "#ffdad6",
        "surface": "#f7f9fb",
        "surface-dim": "#d8dadc",
        "on-primary-container": "#f4fffc",
        "inverse-on-surface": "#eff1f3",
        "secondary-container": "#dae2fd",
        "on-secondary-container": "#5c647a",
        "on-primary-fixed": "#00201d",
        "on-error-container": "#93000a",
        "surface-container": "#eceef0",
        "on-tertiary-fixed": "#0b1c30",
        "surface-container-low": "#f2f4f6",
        "tertiary-fixed": "#d3e4fe",
        "tertiary": "#4d5d73",
        "on-secondary-fixed": "#131b2e",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "on-background": "#191c1e",
        "primary-container": "#008378",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "inverse-surface": "#2d3133",
        "secondary": "#565e74",
        "outline-variant": "#bcc9c6",
        "on-primary-fixed-variant": "#005049",
        "on-tertiary-container": "#fdfcff",
        "inverse-primary": "#6bd8cb",
        "primary-fixed": "#89f5e7",
        "error": "#ba1a1a"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "16px",
        "md": "16px",
        "sm": "8px",
        "xs": "4px",
        "lg": "24px",
        "2xl": "48px",
        "sidebar-width": "260px",
        "base": "4px",
        "gutter": "24px",
        "xl": "32px"
      },
      fontFamily: {
        "headline-md": ["Hanken Grotesk"],
        "headline-lg": ["Hanken Grotesk"],
        "display": ["Hanken Grotesk"],
        "label-md": ["Hanken Grotesk"],
        "headline-lg-mobile": ["Hanken Grotesk"],
        "body-lg": ["Hanken Grotesk"],
        "body-md": ["Hanken Grotesk"],
        "label-sm": ["Hanken Grotesk"]
      },
      fontSize: {
        "headline-md": ["20px", {"lineHeight": "28px", "fontWeight": "500"}],
        "headline-lg": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "500"}],
        "display": ["30px", {"lineHeight": "36px", "letterSpacing": "-0.02em", "fontWeight": "500"}],
        "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "500"}],
        "headline-lg-mobile": ["20px", {"lineHeight": "28px", "fontWeight": "500"}],
        "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "label-sm": ["11px", {"lineHeight": "14px", "letterSpacing": "0.03em", "fontWeight": "500"}]
      }
    },
  },
  plugins: [],
}
